# Generated by Django 4.2.7 on 2023-12-19 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoryTitel', models.TextField(unique=True)),
                ('ganer', models.CharField(choices=[('actions', 'actions'), ('deram', 'deram'), ('harror', 'harror'), ('fantesy', 'fantesy')], max_length=20)),
                ('summary', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('CreatedTime', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_papular', models.BooleanField(default=False)),
                ('is_papular_counter', models.PositiveIntegerField(default=0)),
                ('is_editors_love', models.BooleanField(default=False)),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapterTitel', models.TextField(unique=True)),
                ('Section', models.TextField()),
                ('PublishDateTime', models.DateTimeField(auto_now=True)),
                ('CreatedTime', models.DateTimeField(auto_now=True)),
                ('ForStory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storys')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
